services:
  stats-server:
    build: ./stats
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statDB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:16.1
    container_name: stat-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=statDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmMainDB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  ewm-db:
    image: postgres:16.1
    container_name: ewm-main-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmMainDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
